# Generated by Django 4.2.7 on 2025-03-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Sure numarası', unique=True)),
                ('name_arabic', models.CharField(help_text='Surenin Arapça adı', max_length=255)),
                ('name_turkish', models.CharField(help_text='Surenin Türkçe adı', max_length=255)),
                ('name_english', models.CharField(help_text='Surenin İngilizce adı', max_length=255)),
                ('revelation_type', models.CharField(choices=[('Meccan', 'Mekki'), ('Medinan', 'Medeni')], help_text='Vahiy tipi', max_length=20)),
                ('verse_count', models.PositiveIntegerField(help_text='Ayet sayısı')),
            ],
            options={
                'verbose_name': 'Sure',
                'verbose_name_plural': 'Sureler',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.PositiveIntegerField(help_text='Ayet numarası')),
                ('text_arabic', models.TextField(help_text='Ayetin Arapça metni')),
                ('text_turkish', models.TextField(help_text='Ayetin Türkçe meali')),
                ('text_transliteration', models.TextField(blank=True, help_text='Ayetin Latin harfleriyle okunuşu', null=True)),
                ('juz', models.PositiveIntegerField(help_text='Cüz numarası')),
                ('page', models.PositiveIntegerField(help_text='Sayfa numarası')),
                ('surah', models.ForeignKey(help_text='Ait olduğu sure', on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Ayet',
                'verbose_name_plural': 'Ayetler',
                'ordering': ['surah__number', 'verse_number'],
                'unique_together': {('surah', 'verse_number')},
            },
        ),
        migrations.CreateModel(
            name='Tafsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Tefsir yazarı', max_length=255)),
                ('text', models.TextField(help_text='Tefsir metni')),
                ('source', models.CharField(blank=True, help_text='Tefsir kaynağı', max_length=255, null=True)),
                ('verse', models.ForeignKey(help_text='Tefsir edilen ayet', on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.verse')),
            ],
            options={
                'verbose_name': 'Tefsir',
                'verbose_name_plural': 'Tefsirler',
                'unique_together': {('verse', 'author')},
            },
        ),
    ]
