# Generated by Django 4.2.7 on 2025-03-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_verses_studied', models.PositiveIntegerField(default=0)),
                ('total_verses_memorized', models.PositiveIntegerField(default=0)),
                ('total_study_time', models.PositiveIntegerField(default=0, help_text='Toplam çalışma süresi (dakika)')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Çalışma İlerlemesi',
                'verbose_name_plural': 'Çalışma İlerlemeleri',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_verses_studied', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Çalışma Oturumu',
                'verbose_name_plural': 'Çalışma Oturumları',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VerseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_studied_at', models.DateTimeField(auto_now_add=True)),
                ('last_studied_at', models.DateTimeField(auto_now=True)),
                ('next_review_date', models.DateField()),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kolay'), (2, 'Kolay'), (3, 'Orta'), (4, 'Zor'), (5, 'Çok Zor')], default=3)),
                ('is_memorized', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verse_studies', to='repetition.studysession')),
            ],
            options={
                'verbose_name': 'Ayet Çalışması',
                'verbose_name_plural': 'Ayet Çalışmaları',
                'ordering': ['next_review_date'],
            },
        ),
    ]
